### ISSUE TITLE
Síntesis Noelia

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/actividad-3-sintesis-NoeliaGlez#2]
[sintesis.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-NoeliaGlez/files/12515581/sintesis.pdf)

**Comment by Aricel117** [comment]
Calif: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
